### PR TITLE
Fixes #8521: Don't report error when the copy of the license file for CFEngine Enterprise fails

### PR DESCRIPTION
**Pull request by ncharles**
https://www.rudder-project.org/redmine/issues/8521

### CODE REVIEW

**Comment by peckpeck** [comment]
@ncharles you can merge this now

**Comment by jooooooon** [comment]
Ping @ncharles, please merge this manually using the command above

**Comment by ncharles** [comment]
OK, merging this PR

**Comment by ncharles** [comment]
OK, merging this PR

**Pull request merged**
