### PR TITLE
Fixes #7508: The rudder-agent cron on AIX uses if then, which makes some security test fails

### PR DESCRIPTION
**Pull request by jooooooon**
https://www.rudder-project.org/redmine/issues/7508

### CODE REVIEW

**Comment by ncharles** [comment]
didn't you forget initial promises ?

**Comment by jooooooon** [comment]
PR updated

**Comment by jooooooon** [comment]
> didn't you forget initial promises ?

Good catch. For some reason the same code is in a different file... caught me out :/

**Comment by ncharles** [comment]
yeah, i've noticed the cron part is really different on both block of code

**Pull request merged**
