### PR TITLE
Fixes #8599: UserManagement 6.0 on at least Debian fails to add user if the user's default group already exists

### PR DESCRIPTION
**Pull request by ncharles**
https://www.rudder-project.org/redmine/issues/8599

### CODE REVIEW

**Comment by amousset** [comment]
Reproduced on CentOS 7.1, so the _debian_ condition is probably not the right one.

**Comment by ncharles** [comment]
Commit modified

**Comment by ncharles** [comment]
it's not mandatory on sles, but it doesn't break to use it

**Comment by ncharles** [comment]
Commit modified

**Comment by ncharles** [comment]
Commit modified

**Comment by ncharles** [comment]
OK, merging this PR

**Comment by ncharles** [comment]
OK, merging this PR

**Pull request merged**
