### PR TITLE
Fixes #6578: Upload inventory with https by default

### PR DESCRIPTION
**Pull request by peckpeck**
http://www.rudder-project.org/redmine/issues/6578

### CODE REVIEW

**Comment by peckpeck** [comment]
@ncharles ping

**Comment by ncharles** [comment]
sorry, i missed this PR :( you should ping me on IRC for this.
Looks good to me, be you ought to rebase it now

**Comment by ncharles** [comment]
please rebase and self merge

**Comment by peckpeck** [comment]
PR updated

**Comment by peckpeck** [comment]
OK, self merging.

**Pull request merged**
