### PR TITLE
Fixes #7772: Agent processes parts of the environment (multiline bash variables) on systems without \"env --null\" support

### PR DESCRIPTION
**Pull request by jooooooon**
https://www.rudder-project.org/redmine/issues/7772

### CODE REVIEW

**Comment by jooooooon** [comment]
PR updated

**Comment by jooooooon** [comment]
PR updated

**Comment by jooooooon** [comment]
Rebased to include the fix from #7774

**Comment by jooooooon** [comment]
PR updated

**Comment by peckpeck** [comment]
OK, merging

**Pull request merged**
