### PR TITLE
Fixes #12603: Wrong reporting in "ManagekeyValue" technique

### PR DESCRIPTION
**Pull request by Fdall**
https://www.rudder-project.org/redmine/issues/12603

Replacing previous PR: https://github.com/Normation/rudder-techniques/pull/1292

### CODE REVIEW

**Comment by amousset** [comment]
Could you rebase to 1 commit?

**Comment by Fdall** [comment]
PR rebased

**Comment by Fdall** [comment]
PR rebased

**Comment by Fdall** [comment]
Commit modified

**Comment by Fdall** [comment]
Commit modified

**Pull request merged**
