### PR TITLE
Fixes #6082: Make CFEngine binaries usable by everyone (mode 755)

### PR DESCRIPTION
**Pull request by jooooooon**
https://www.rudder-project.org/redmine/issues/6082

### CODE REVIEW

**Comment by jooooooon** [comment]
PR updated

**Comment by ncharles** [comment]
Why targeting only branch 3.2 ?
Default cfengine installs have 755 or all binaries

**Comment by jooooooon** [comment]
> Why targeting only branch 3.2 ?
> Default cfengine installs have 755 or all binaries

This is a significant change. If users have audited a Rudder installation, and care about file perms, we should not make a change like this in a patch version.

**Comment by ncharles** [comment]
Oh, ok then

**Pull request merged**
