### PR TITLE
Fixes #9125: Add a technique using new package promises

### PR DESCRIPTION
**Pull request by amousset**
https://www.rudder-project.org/redmine/issues/9125

### CODE REVIEW

**Comment by amousset** [comment]
PR updated.

**Comment by amousset** [comment]
Commit modified

**Comment by amousset** [comment]
@ncharles Added pass2 for methods.

**Comment by ncharles** [comment]
This looks great. However, it works only with cfengine 3.7+ - but Rudder 3.2 server may have Rudder 3.1 agent 
I'm not sure there are any system to prevent policies generation from failing - are you aware of any ?

**Comment by amousset** [comment]
Commit modified

**Comment by ncharles** [comment]
\o/

**Pull request merged**
