### PR TITLE
Fixes #8436: Getting server uuid fails on agent with old openssl

### PR DESCRIPTION
**Pull request by peckpeck**
https://www.rudder-project.org/redmine/issues/8436

### CODE REVIEW

**Comment by peckpeck** [comment]
ping @amousset

**Comment by peckpeck** [comment]
Very old pr since june 12 @amousset

**Comment by amousset** [comment]
Do we know what is the real cause of the issue? We know it works on SLES11 at least in some cases. This PR seems to reallow SSLv2/3 which does not look like a good solution if not strictly necessary.

**Comment by peckpeck** [comment]
It does, on old sles.
We should ask the bug reporter if we want more information on the condition, but it seems blurry

**Comment by peckpeck** [comment]
An up to date sles should have an up to date openssl.
Lets' package openssl for very old os instead.

**Pull request closed without merging**
