### PR TITLE
Fixes #7785: Rudder inventory don't produce error report

### PR DESCRIPTION
**Pull request by amousset**
https://www.rudder-project.org/redmine/issues/7785

### CODE REVIEW

**Comment by amousset** [comment]
`could_not_download_uuid` is not in the abortclasses in technique, but only in initial-promises. @ncharles do you know if there is a reason for this?

**Comment by jooooooon** [comment]
I think it may be to prevent the agent from trying to send an inventory if it can't contact it's server

**Comment by peckpeck** [comment]
Then adding such a tech before sending the inventory is a better solution.

**Comment by ncharles** [comment]
Sorry, I didn't see the question. The goal of having this class was indeed to prevent bogus inventory to be sent. But indeed, now promises changed, and this should not plainly abort. Merging

**Pull request merged**
