### PR TITLE
Fixes #7690: Use classic protocol in Rudder 3.2

### PR DESCRIPTION
**Pull request by amousset**
https://www.rudder-project.org/redmine/issues/7690

### CODE REVIEW

**Comment by peckpeck** [comment]
OK, good, but why not in 2.11 ? especially for system techniques

**Comment by peckpeck** [comment]
Lets backport it later

**Comment by ncharles** [comment]
protocl_version was introduced in 3.6, so won't work on 3.5
We need to keep the compatibility with previous version of Rudder in Rudder <3.1 (unless stated otherwise)
So only Rudder 3.2 will have this fix

**Comment by peckpeck** [comment]
2.11 if cfengine 3.6
And older server will give their promises to newer agents from their system techniques, so newer agent won't be able to talk to older server.

**Comment by ncharles** [comment]
@peckpeck no, server 2.11 may still server agent 2.10, and so it will break.

**Comment by ncharles** [comment]
and if you use agent 3.2 with server 2.11, it will use classic protocol, same for agent 3.1 with server 3.2

**Comment by peckpeck** [comment]
It detects the server version before choosing the protocol ?

**Comment by ncharles** [comment]
CFEngine 3.6 uses classical by defaut.
If any of the two use classical, the protocol used is classical

**Comment by peckpeck** [comment]
ok

**Comment by ncharles** [comment]
this is why agent 3.1 + server 3.2 works with NAT system, but without this patch, agent 3.2 and server 3.2 does not

**Comment by amousset** [comment]
yes but agent 3.2 with any server from 2.11 will use TLS as it is supported by the server.

**Pull request merged**
