### PR TITLE
Fixes #12348: Correct path to permlist file in File Permissions in 4.3

### PR DESCRIPTION
**Pull request by ncharles**
https://www.rudder-project.org/redmine/issues/12348

### CODE REVIEW

**Comment by ncharles** [comment]
Don't merge for now

**Comment by ncharles** [comment]
@amousset if I drop the OUTPATH from the metadata, permlist is correctly generated, but with a .cf - do you think it would be an issue ?

**Comment by amousset** [comment]
What is the current status of this PR?

**Comment by ncharles** [comment]
You may merge it !

**Pull request merged**
