### PR TITLE
Fixes #13992: Cleanup rudder promises generated

### PR DESCRIPTION
**Pull request by peckpeck**
https://issues.rudder.io/issues/13992

### CODE REVIEW

**Comment by ncharles** [comment]
and rudder agent health also

**Comment by peckpeck** [comment]
PR rebased

**Comment by peckpeck** [comment]
i don't see any reference in rudder agent health

**Comment by ncharles** [comment]
> i don't see any reference in rudder agent health

indeed, my bad, i mistoke it for rudder_promises_updated

**Pull request merged**
