### PR TITLE
Fixes #8034: When we manage twice a same package in rpm package management, we don't get the second report

### PR DESCRIPTION
**Pull request by ncharles**
https://www.rudder-project.org/redmine/issues/8034

### CODE REVIEW

**Comment by ncharles** [comment]
WIP
must do also previous versions

**Comment by ncharles** [comment]
ha, actually previous version don't use the methods: for reporting, so good to merge

**Comment by ncharles** [comment]
PR updated

**Comment by ncharles** [comment]
PR updated

**Comment by amousset** [comment]
Ok, merging.

**Pull request merged**
