### PR TITLE
Fixes #7274: Remove periodic cf-execd and cf-serverd restart at 05:00

### PR DESCRIPTION
**Pull request by Kegeruneku**
Ticket: http://www.rudder-project.org/redmine/issues/7274

To be merged in 2.10

### CODE REVIEW

**Comment by Kegeruneku** [comment]
Note: I think this is the wrong approach, we should just remove this bundle altogether (cf http://www.rudder-project.org/redmine/issues/6118 )

**Comment by Kegeruneku** [comment]
Should I remove it instead ?

**Comment by Kegeruneku** [comment]
I chose to merge the cron setup altogether in one single file (KISS)

**Comment by peckpeck** [comment]
OK Good

**Pull request merged**
