### PR TITLE
Fixes #22724: Reporting error when using a dash for SSH authorized keys method

### PR DESCRIPTION
**Pull request by Fdall**
https://issues.rudder.io/issues/22724

### CODE REVIEW

**Review by amousset — APPROVED** [review]

**Comment by Fdall** [comment]
PR updated with a new commit

**Comment by Fdall** [comment]
PR updated with a new commit

**Comment by Fdall** [comment]
PR updated with a new commit

**Comment by Fdall** [comment]
PR rebased

**Comment by Fdall** [comment]
PR updated with a new commit

**Comment by Fdall** [comment]
OK, squash merging this PR

**Pull request merged**
