### PR TITLE
Fixes #7638: Rudder agent connect at each runs to its policy server to get its server uuid

### PR DESCRIPTION
**Pull request by jooooooon**
https://www.rudder-project.org/redmine/issues/7638

### CODE REVIEW

**Comment by jooooooon** [comment]
Upmerging this into following branches will be HARD, so please DON'T merge this once the review is OK, but instead signal your approval to me, and I will manually merge and upmerge it at once.

**Comment by jooooooon** [comment]
@ncharles Could you review this please?

**Comment by ncharles** [comment]
This looks ok, but why isn't the initial promises modified also ?

**Comment by jooooooon** [comment]
Commit modified

**Comment by jooooooon** [comment]
PR rebased

**Comment by jooooooon** [comment]
Do not merge for now, this is screwed up for some reason

**Comment by jooooooon** [comment]
Commit modified

**Comment by ncharles** [comment]
Actually, I don't see any changes

**Comment by jooooooon** [comment]
Yeah GitHub seems to be broken at the moment. Give it a few hours...

**Comment by jooooooon** [comment]
OK, GitHub is OK again. Ready for review again @ncharles

**Comment by ncharles** [comment]
looks good

**Pull request merged**
