### PR TITLE
Fixes #7417: Merge error from #7190 - extra code appeared in 3.1 branch (that does nothing harmful)

### PR DESCRIPTION
**Pull request by jooooooon**
https://www.rudder-project.org/redmine/issues/7417

### CODE REVIEW

**Comment by jooooooon** [comment]
Actually please don't merge this yet, a piece is missing

**Comment by jooooooon** [comment]
PR updated

**Comment by jooooooon** [comment]
PR updated

**Comment by jooooooon** [comment]
OK, good to go again

**Comment by ncharles** [comment]
such weirdness

**Pull request merged**
