### PR TITLE
Fixes #15738: sshKeyDistribution breaks root perms when target user has no home defined

### PR DESCRIPTION
**Pull request by Fdall**
https://issues.rudder.io/issues/15738

### CODE REVIEW

**Comment by peckpeck** [comment]
you should applys the same patch to version 3.0 that still exists in rudder 5.0

**Comment by Fdall** [comment]
PR updated with a new commit

**Comment by Fdall** [comment]
OK, squash merging this PR

**Comment by Fdall** [comment]
OK, merging this PR

**Pull request merged**
