### PR TITLE
Fixes #11791: Allow configuring a proxy for HTTP(S) communication between agent and policy server

### PR DESCRIPTION
**Pull request by ncharles**
https://www.rudder-project.org/redmine/issues/11791

### CODE REVIEW

**Comment by ncharles** [comment]
Commit modified

**Comment by ncharles** [comment]
There are others proxies usage in the promises, but only for the server, to localhost itself, so I skipped them

**Comment by amousset** [comment]
Looks good to me

**Comment by ncharles** [comment]
Do not merge, this is only a workaround

**Comment by ncharles** [comment]
Replaced by https://github.com/Normation/rudder-techniques/pull/1244

**Pull request closed without merging**
