### PR TITLE
Fixes #8853: Download technique-files from Rudder website

### PR DESCRIPTION
**Pull request by amousset**
https://www.rudder-project.org/redmine/issues/8853

### CODE REVIEW

**Comment by jooooooon** [comment]
@amousset Don't forget to change the CI jobs to run "make test"

**Comment by amousset** [comment]
I will change the build tasks to run `make test` after it is merged.

**Comment by amousset** [comment]
Too fast ;)

**Comment by amousset** [comment]
OK, merging this PR

**Comment by amousset** [comment]
OK, merging this PR

**Pull request merged**
