### PR TITLE
Fixes #9003: Update modules from ncf internal in Rudder's failsafe

### PR DESCRIPTION
**Pull request by amousset**
https://www.rudder-project.org/redmine/issues/9003

### CODE REVIEW

**Comment by amousset** [comment]
WIP, do not merge.

**Comment by amousset** [comment]
* Should we check at each run or only when ncf/common was repaired?
* Should we handle local modules ? In this case, we need to handle the case were the modules folder does not exist.

**Comment by ncharles** [comment]
I think we should use the same method for update, so copy the module only if the hash of the ncf was updated
And we need to create the modules folder if it doesn't exists

**Comment by jooooooon** [comment]
I don't think this should be done here at all. As explained in the ncf source code in Normation/ncf#427, copying these files is required for the new package_* methods in ncf to work. Therefore, ncf should do it itself if necessary.

This may require adding a "ncf initialisation" bundle that is called by Rudder, very early in the bundlesequence, if we don't already have one, but that's fine, since it's not a hard change, and I'm sure it will come in for other reasons.

Also, I don't like this being in update.cf because this isn't really a copy from the server, it's just a local copy, so that doesn't need to be done at a specific point in time - unless of course these files are loaded on cf-agent startup rather than when a packages: promise is called?

**Comment by ncharles** [comment]
Updating parts of files of workdir outside the update will be pretty surprising - it is a big change from the way files in this folder are handled in both Rudder and CFEngine usually, and it will surprise users trying to understand why content of modules folder change outside of the update

**Comment by jooooooon** [comment]
> Updating parts of files of workdir outside the update will be pretty surprising - it is a big change from the way files in this folder are handled in both Rudder and CFEngine usually, and it will surprise users trying to understand why content of modules folder change outside of the update

Lots of parts of the workdir are changed outside update - outputs are written at the end of a run, package lists are written during the run, the whole state directory is updated during the run, the ncf.conf.cache file is generated during the run, ncf's expected promises files are generated during the run, ...

Let's not get caught up in internal details here please - this is a ncf requirement, it belongs in ncf.

**Comment by ncharles** [comment]
`Let's not get caught up in internal details here please - this is a ncf requirement, it belongs in ncf.`

Same as propagating in some way to the nodes the folders 10, 20, 30, etc that belong in ncf - yet they are updated with rudder

**Comment by ncharles** [comment]
I doubled checked with CFEngine vanilla implementation: by default, they do not purge the modules folder when copying it, so we can populate it from outside an update.cf (even if it will be surprising for user, it won't be non-convergent)

**Comment by amousset** [comment]
Updating the modules from outside the update process is indeed against the "masterfiles way". However, if we want ncf to stay, as much as possible (because files loading is a big exception), an independent framework, used by Rudder policies, it is probably a better idea to use a defined and stable API like an init bundle that to interfere with ncf internals (even if in this case modules are both internal for ncf and global for the agent).

We can add this call to ncf init in system techniques (but won't be able to call it from update.cf as it would require to load ncf). I think we also need to add a report for this step, as it is important and does not match any of current reports.

**Comment by fanf** [comment]
It seems to have a consensus on that way of doing the update. So I'm closing that PR as the code will live in ncf.

**Pull request closed without merging**
