### PR TITLE
Fixes #7501: Set TZ of Beijing

### PR DESCRIPTION
**Pull request by matya**

### CODE REVIEW

**Comment by jooooooon** [comment]
Thanks for retargeting @matya!

I'm going to ask you for one more effort... If you look at the "Commits" tab in this PR, you'll notice there are 4 commits in total, 1 for your actual fix and 3 "merge" commits. They are not harmful by their content (the diff is just fine), but they do introduce confusion in the git history ("git log"). Basically, extra commits means more commits to look through when analysing a bug, and merge commits are always suspicious :) So, could you rebase the branch you made this PR from?

Rough instructions would be:
1) git rebase -i origin/branches/rudder/2.11
2) In the editor that appears, delete all commits (one per line) except the actual commit that fixes this bug, and save
3) git push --force <your repo>

This will "rewrite history", because you are eliminating those merge commits to just add your bug fix on top of existing 2.11 branch from the main repo.

Sorry to keep making you work, but I'm also hoping this will be useful to you, and help to streamline future contributions (to Rudder or other projects on GitHub) :)

**Comment by matya** [comment]
Yeah sorry, I used the github.com Web GUI to do the changes, will rework it
as soon I get to it. Or maybe you can fix that one liner by an own pr :)

Jonathan Clarke <notifications@github.com> ezt írta (időpont: 2015. nov.
30., H 10:45):

**Comment by jooooooon** [comment]
I certainly can - I just didn't want to steal your thunder :)

I'll do that, then.

**Comment by jooooooon** [comment]
Replaced by #808

**Pull request closed without merging**
