### PR TITLE
Fixes #11803: On update error, the help message is not valid anymore

### PR DESCRIPTION
**Pull request by peckpeck**
https://www.rudder-project.org/redmine/issues/11803

### CODE REVIEW

**Comment by amousset** [comment]
Shouldn't this got to 4.1 instead?

**Comment by peckpeck** [comment]
4.1 agent can communicate with 3.1 servers which still have  this issue

**Comment by amousset** [comment]
Once 4.1 promises are in place the agent will never use the old protocol, it may only happen with 3.1 agents with initial promises, which use the 3.1 branch of rudder-techniques

**Comment by peckpeck** [comment]
PR replaced by https://github.com/Normation/rudder-techniques/pull/1225

**Pull request closed without merging**
