### PR TITLE
Fixes #22402: A 6.2 relay cannot talk to a 7.2 server through HTTPS

### PR DESCRIPTION
**Pull request by amousset**
https://issues.rudder.io/issues/22402

### CODE REVIEW

**Comment by amousset** [comment]
not good

**Comment by amousset** [comment]
PR updated with a new commit

**Comment by amousset** [comment]
PR updated with a new commit

**Comment by amousset** [comment]
PR updated with a new commit

**Review by ncharles — APPROVED** [review]

**Pull request merged**
