### PR TITLE
Fixes #11336: Technique "Package sources and settings (APT)" does not support stretch

### PR DESCRIPTION
**Pull request by VinceMacBuche**
https://www.rudder-project.org/redmine/issues/11336

### CODE REVIEW

**Comment by amousset** [comment]
https://wiki.debian.org/fr/DebianBuster?

**Comment by VinceMacBuche** [comment]
Commit modified

**Comment by VinceMacBuche** [comment]
Commit modified

**Comment by VinceMacBuche** [comment]
Commit modified

**Pull request merged**
