### PR TITLE
Fixes #6501: reports/all.log logs everything, not just rudder logs

### PR DESCRIPTION
**Pull request by peckpeck**
http://www.rudder-project.org/redmine/issues/6501

### CODE REVIEW

**Comment by ncharles** [comment]
This wont work: messages from the remote agent are not in local6
this change won't log them ..
You'll want to check by program name, like in what is done at the end of the file
:programname, contains, "rudder"  /var/log/rudder/reports/all.log
:msg, ereregex, "from .*: rudder:"  /var/log/rudder/reports/all.log

**Comment by peckpeck** [comment]
Yes they are, why wouldn't they be ?
All rudder messages are in local6, whether from local or remote agent.

**Comment by jooooooon** [comment]
This looks like a nice fix to have - @peckpeck could you rework it for master branch (I don't think we should make a behavioural change like this in a released version) and get @amousset to review it please?

**Comment by peckpeck** [comment]
PR replaced by https://github.com/Normation/rudder-techniques/pull/1185

**Pull request closed without merging**
